### ISSUE TITLE
Steady Breath Affecting Attacker's CD

### ISSUE THREAD

**Issue by ChakaKhan** [winsomniak/kagero-calc#1]
While running calcs of B!Lyn versus the various dragons, I found that she is being given an extra special charge when getting counter attacked when she is the attacker. Tested it out on various combos (100% reproduction rate), bug looks to be as follows:

1. Attacker with 3 CD special initiates on defender with Steady Breath and can counter attack (melee vs melee, ranged vs melee+DC, ranged vs ranged).

2. Attacker gains 1 charge (normal), defender gains 2 charge (normal)

3. Defender counter-attacks

4. Attacker gains 2 charge (not normal), defender gains 2 charge (normal)

5. Attacker follows up (if outspeeds) and activates the special

This bug gets more interesting once Quick Riposte is factored in because if the defender has QR up, a 6 charge special (Aether+Lighting Breath for example), and is doubled, then they do not activate their special on the bonus follow-up.

**Comment by winsomniak** [comment]
This is a fairly complex problem due to the combat engine's logic. If someone else wants to look over it and suggest and/or fix that would be fantastic.

Its likely a logical error but I won't be able to dive deep on this one while in the middle of a move.

Thanks for reporting @ChakaKhan

**Comment by Lorenzooone** [comment]
Found the logical error: I'll try fixing it.

**Comment by winsomniak** [comment]
Awesome @Lorenzooone 

Were you able to set yourself up for testing locally? I have not added instructions to the readme/wiki yet.

**Comment by Lorenzooone** [comment]
I had to manually trace it, no big deal.

**Comment by Lorenzooone** [comment]
Done. It was a "attacker" misplaced.

**Comment by winsomniak** [comment]
This is fixed. Thanks @Lorenzooone
