### ISSUE TITLE
Clair 4* merges

### ISSUE THREAD

**Issue by Brettops** [winsomniak/kagero-calc#108]
I just started making a 4*+10 Clair, currently at +4 I had to backtrack and check what her IVs were so I tried to check them through the site. At +4 regardless of boon or bane I couldn't get the stats I have currently on my L1 4*+4 Clair. I made sure she had no skills, the right weapon, everything. She's +Atk -Res with 19/20/10/5/9 stats, on your site the same +4 Clair is showing 19/19/10/5/10. At 4 merges it seems it picked to increase both Speed and Res instead of Attack and Speed which it should have (Attack is 2nd highest so it gets increased at 1 and 4 merges) and since Speed and Res are tied it goes to the first stat slot which is Speed. I think it might be something to do with both Speed and Res being the same value but I can't test if that is true since 2 merges would have both Speed and Res being increased since they're tied for 3rd highest value. 
Should be for +Atk -Res:
+0: 17/18/8/4/8
+1: **18**/**19**/8/4/8
+2: 18/19/**9**/4/**9**
+3: **19**/19/9/**5**/9
+4: 19/**20**/**10**/5/9 ==> you're showing it as 19/19/**10**/5/**10**
+5: 19/20/10/**6**/**10**
+6: **20**/**21**/10/6/10
+7: 20/21/**11**/6/**11**
+8: **21**/21/10/**7**/11
+9: 21/**22**/**12**/7/11 ==> another possible case where it would show 21/21/**12**/7/**12**
+10: 21/22/11/**8**/**12**
I can only confirm the +4 stat line, but based on what got increased I can assume it regard Attack as 2nd highest and Speed as 3rd highest due to being the first stat on the list (HP>Atk>Spd>Def>Res for tie breaks) despite Attack being the second lowest base stat only being 7 with boon and no weapon. I'm not entirely sure whether the game picks based off of the unit's base stats including the weapon they would have or without any weapon, in this case it appears to use the weapon Mt in the selection since +4 (according to gamepedia's merging page) increases the 2nd and 3rd highest stat and I got Atk and Spd raised.

Edit: Pulled another Clair and merged her in for +5, Def and Res got increased as expected, so +4 and +5 are confirmed.

**Comment by Lorenzooone** [comment]
Weapons aren't counted in the merges, I'm sure of it.
What's really strange is the fact that you say those are your stats... Do you have a screen of your old 4* +4? (Not saying you're lying, but double checking)
I'd ask reddit about this if I were you, since maybe someone may be able to replicate it... I'm really confused by this... Even https://feh-stuff.github.io/unit-builder/ says the same thing as us.

**Comment by Brettops** [comment]
I didn't get a screenshot of my old Clair and I deleted the one I had of the +5 Clair since it wouldn't have helped (taken after the stat buffs came). I'll try to get one for the +9 since it would probably be the same issue or if I find myself swimming in Clair's make another +4 to check, but I'm 100% sure those were my stats since it did buff my Def and Res with the +5 instead of Atk and Def. 

 I do agree though that this is weird since I thought weapons weren't counted but it appears to be in this case, could be an 'old' unit thing since Clair was released a couple months after the game came out but that seems unlikely. 

I might be able to get a friend to test, if not I'll put it over on Reddit and see if they can recreate it.

**Comment by Brettops** [comment]
Update, friend had the right IVs and made a new one that shows the buffs as well for +4:
![clair](https://user-images.githubusercontent.com/17712744/42404078-0188807c-8154-11e8-9c50-9784598badd8.png)

**Comment by Lorenzooone** [comment]
I'm trying to pinpoint the issue: were both summoned at 4* or upgraded to 4*?

**Comment by Lorenzooone** [comment]
Because if this is what I think it is, it's wild.

**Comment by Lorenzooone** [comment]
So what I have in mind is that it uses the base stats as a 1*, applies the IVs and then chooses the order for merges. If we went with this hypotesis, it would explain why you have such a strange growth.

**Comment by Lorenzooone** [comment]
Since a 5* is +2 to every stat from 1*, no one noticed because it was all okay, but with lower rarities, things change.
