### ISSUE TITLE
Breath of Fog missing

### ISSUE THREAD

**Issue by kitsuneamira** [winsomniak/kagero-calc#110]
As the title suggests, Breath of Fog is missing as a weapon option for Tiki(A) in the combat simulator.

Also I'm sure this has already been brought up, but a number of newer Heroes are missing from the simulator as well.

**Comment by Lorenzooone** [comment]
The update is ready, once the portraits are ready too, the update will be live. https://github.com/winsomniak/kagero-calc/pull/109

**Comment by winsomniak** [comment]
This is in last update
