### ISSUE TITLE
Stats Below Minimum Set to 1, Adding/Removing Skills Bring Stats to Incorrect Values

### ISSUE THREAD

**Issue by winsomniak** [winsomniak/kagero-calc#27]
As reported by Moxie on Discord

"man if ogma came as a 1* unit will his res go into the negatives oh hey there's abug on kagchart if you put LD on -res lv 1 Ogma(edited) and then take it off it puts his res back at...6 and not 1 edge cases! @Moxie probably should let winsomniak know"

**Comment by winsomniak** [comment]
I confirmed this one, but its quite old.

**Comment by YukariTea** [comment]
Additionally, the minimum stat should be 0, not 1.

**Comment by winsomniak** [comment]
Fix might be pretty involved, since there are many places in the code that decrease stats.

**Comment by Lorenzooone** [comment]
Fixed in the next update. https://github.com/winsomniak/kagero-calc/commit/02e695e3236deed01862cf428f101539cbf3daa0
