### ISSUE TITLE
Lower ranks of Cancel Affinity function incorrectly

### ISSUE THREAD

**Issue by winsomniak** [winsomniak/kagero-calc#28]
*Reported via email, confirmed by myself*

This one is pretty old but potentially challenging. I put it off because it deals specifically with lower ranking abilities, which aren't a huge priority for most people.

**Details**

When Cancel Affinity 3 is in effect against a Triangle Adept 3 or Gem Weapon user, who would normally have a 40% bonus against an enemy due to the combined 20% of the weapon triangle advantage bonus and the 20% adept bonus, the calculator applies a -40% penalty, resulting in a 0% bonus, as if a unit had no triangle advantage at all. This is the correct result. 

However, when Cancel Affinity 3 is in effect against a Triangle Adept 1 or Triangle Adept 2 user, who would normally have a 30/35% bonus against an enemy due to the combined 20% of the weapon triangle advantage bonus and the 10/15% adept bonus, the calculator still applies a -40% penalty. This results in a -10/-5% penalty, where it should be a 10/5% bonus. 

Cancel Affinity 3 reverses the adept bonuses of enemy units, meaning that the 20% weapon triangle advantage bonus and a 10% adept bonus would become a 20% weapon triangle advantage bonus and a -10% penalty, resulting in a 10% bonus. Please fix this error so I can see exactly how well Triangle Adept 1 or Triangle Adept 2 users actually perform against Cancel Affinity 3 users.

**Comment by winsomniak** [comment]
We tested this one right?

**Comment by Lorenzooone** [comment]
Yup. It's been fixed!
