### ISSUE TITLE
Brash assault seal display issue

### ISSUE THREAD

**Issue by winsomniak** [winsomniak/kagero-calc#37]
See forum: https://community.gamedex.io/t/display-issue-on-brash-assault-desperation-in-calc/420/2

This is related to the [redundant logic rewrite](https://github.com/winsomniak/kagero-calc/issues/33) I'm proposing. These type of problems would more or less disappear if we didn't have such specific engine logic.

**Comment by Lorenzooone** [comment]
Fixed in the last update (the follow logic one)
