### ISSUE TITLE
Upgraded staves have no effect

### ISSUE THREAD

**Issue by YukariTea** [winsomniak/kagero-calc#49]
Slow+, Fear+, Absorb+, Pain+, and Panic+ do not function properly (their non plus counterparts have proper effects).
This bug affects data outside this repository.

Links to reproduce:
- https://kagerochart.com/damage-calc?char-1=lachesis-lionhearts-sister&rarity-1=5&level-1=40&weapon-1=absorb-plus&char-2=sophia-nabata-prophet&rarity-2=5&level-2=40
- https://kagerochart.com/damage-calc?char-1=clarine-refined-noble&rarity-1=5&weapon-1=fear-plus
- https://kagerochart.com/damage-calc?char-1=wrys-kindly-priest&rarity-1=5&weapon-1=slow-plus
- https://kagerochart.com/damage-calc?char-1=azama-carefree-monk&rarity-1=5&weapon-1=pain-plus
- https://kagerochart.com/damage-calc?char-1=priscilla-delicate-princess&rarity-1=5&weapon-1=panic-plus

**Comment by Lorenzooone** [comment]
Yeah, as expected. I'll add them to the weapons.json. Might as well add the missing refinable weapons in the meantime.
