### ISSUE TITLE
Kadomatsu and Kadomatsu+ have Incorrect Range

### ISSUE THREAD

**Issue by ObsceneSoul** [winsomniak/kagero-calc#52]
The weapons Kadomatsu and Kadomatsu+ have an incorrect range of 2 as opposed to the correct range of 1, causing them to counter-attack and not counter at the incorrect times.

**Comment by Lorenzooone** [comment]
https://github.com/winsomniak/kagero-calc/issues/13

**Comment by Lorenzooone** [comment]
Even though I closed this because it's a duplicate, thanks for reporting!
