### ISSUE TITLE
Various messages use internal name instead of proper display name

### ISSUE THREAD

**Issue by YukariTea** [winsomniak/kagero-calc#63]
The owl tome effects and the healing message effects use internal names when referring to the source.
Links to reproduce:
* https://kagerochart.com/damage-calc?char-1=mae-bundle-of-energy&rarity-1=5&weapon-1=blarowl-plus&adjacent-1=1
* https://kagerochart.com/damage-calc?char-1=lachesis-lionhearts-sister&rarity-1=5&level-1=40&weapon-1=absorb-plus&char-2=sophia-nabata-prophet&rarity-2=5&level-2=40
* https://kagerochart.com/damage-calc?char-1=alfonse-prince-of-askr&spec-cooldown-1=0

**Comment by winsomniak** [comment]
Looks like @jcjoneskern took care of one of these.
