### ISSUE TITLE
Axebreaker VS Armads + Quick Riposte has incorrect interaction

### ISSUE THREAD

**Issue by YukariTea** [winsomniak/kagero-calc#68]
**Link:**
* https://kagerochart.com/damage-calc?char-1=laslow-dancing-duelist&rarity-1=5&level-1=40&passive-b-1=axebreaker-3&char-2=hector-general-of-ostia&rarity-2=5&level-2=40&weapon-2=armads&passive-b-2=quick-riposte-3

**What should be happening:**
Both Laslow and Hector perform a guaranteed follow-up attack.
Visual: 
![avaq](https://user-images.githubusercontent.com/24845025/35028955-6e6c0862-fb0d-11e7-8185-431ae9f8a63d.png)

**What is incorrectly happening:**
Hector's follow-up attack is determined by speed even though there is still an active effect.

**Comment by Lorenzooone** [comment]
The whole follow-up system is janked up.Instead of following the game's logic it has a logic of his own, resulting in these errors. If you wait until the 19th, I could try to fix it.

**Comment by winsomniak** [comment]
Awesome format on the example there @YukariTea . @Lorenzooone addressed this I think. I'll test once I merge their pull request.

Cheers
