### ISSUE TITLE
Thani doesn't get "effective against" bonus

### ISSUE THREAD

**Issue by Totaliss** [winsomniak/kagero-calc#70]
Title ^
Micaiah's Thani doesn't get the effective against bonus vs armor and cavalry opponents

**Comment by Lorenzooone** [comment]
Duplicate of https://github.com/winsomniak/kagero-calc/issues/60
Thanks for reporting, though. The issue's been worked on.

**Comment by Lorenzooone** [comment]
Duplicate of https://github.com/winsomniak/kagero-calc/issues/60
The issue's being worked on, thanks for reporting though.
