### ISSUE TITLE
Wrath and AoE specials

### ISSUE THREAD

**Issue by YukariTea** [winsomniak/kagero-calc#72]
The skill wrath has been changed in the Ver. 2.2.0 update. It will now trigger the damage +10 effect for Special skills that do damage to foes within a certain range, such as Blazing Thunder.

Links:
* https://kagerochart.com/damage-calc?char-1=navarre-scarlet-sword&weapon-1=killing-edge-plus&special-1=blazing-wind&passive-b-1=wrath-3&spec-cooldown-1=0&curr-hp-1=31

**Comment by Lorenzooone** [comment]
It already did the check, but the code was broken and incremented dmg instead of aoeDmg, fixed it in a next update.
