### ISSUE TITLE
Bold Fighter battles

### ISSUE THREAD

**Issue by XordMastR** [winsomniak/kagero-calc#74]
When an attacker has bold fighter it shows that the attacker makes 3 attacks if they naturally double the defender. Amelia is shown to make 3 attacks on Hector for example because it shows the first attack, the automatic follow up and then a third attack. From what ive seen Bold Fighter only guarantees a double attack instead of allowing an additional one.

**Comment by Lorenzooone** [comment]
Confirm it's fixed in the update (tested)
