### ISSUE TITLE
Weapons issue.

### ISSUE THREAD

**Issue by iMainMarth** [winsomniak/kagero-calc#77]
When I try to simulate combat with Caeda. It gives me the chance to wield Divine Tyrfing while it's restricted to Seliph and his father (can't remember his name atm) and it doesn't display Wing sword as well. And by the way selecting quickened pulse seems to not affect any special cooldown.

**Comment by Lorenzooone** [comment]
The calc is updated to the Radiant Dawn benner... It will take some days to be updated to the latest banner. Quickened Pulse doesn't have anything to do with the battle system. You're the one that has to change the cooldown using the Effectts tab. Hope this helped!

**Comment by winsomniak** [comment]
Quickened pulse does not _do_ anything in the context of the damage calc. We may change this behavior in the future but as @Lorenzooone indicated, you can adjust the cooldown in the status tab.

Big update today or tomorrow, after which I expect many more minor bug reports. Thanks for stopping by to point out these problems!

@Lorenzooone did any of your updates assign the char_unique attribute to Divine Tyrfing?

**Comment by Lorenzooone** [comment]
They didn't... I have to push something quick to fix a little error in the hardy bearing thing, so I'll put it there.

**Comment by Lorenzooone** [comment]
https://github.com/winsomniak/kagero-calc/pull/80

**Comment by winsomniak** [comment]
Sweet thanks
