### ISSUE TITLE
Calculation Error LA!Eliwood vs Lukas

### ISSUE THREAD

**Issue by TimesLuigi** [winsomniak/kagero-calc#90]
Default match up of Eliwood attacking Lukas and calculator says eliwood will be dealing 35 damage per attack. Last time I checked 52 atk vs 43 def does not equal 35 damage.

Did some calcs and it looks like it's using Lukas Res stat in the calculation instead of his Def stat.

**Comment by Lorenzooone** [comment]
It's already been fixed in a previous pull request, please wait for the update.

**Comment by Lorenzooone** [comment]
Fixed.
